// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include <iostream>

#include "distData.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::comProto;

class distDataHandler : virtual public distDataIf {
 public:
  distDataHandler() {
    // Your initialization goes here
  }

  void runCmd(result& _return, const std::string& command) {
    // Your implementation goes here
    std::cout << "command: " << command << std::endl;
    printf("runCmd\n");
  }

  void runCmdWParms(result& _return, const execWParms& command) {
    // Your implementation goes here
    printf("runCmdWParms\n");
  }

  int32_t ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void listFilesDir(directory& _return, const std::string& DirPath, const std::string& workingDir) {
    // Your implementation goes here
    printf("listFilesDir\n");
  }

  void mvFile(result& _return, const std::string& FileName, const std::string& workingDir, const std::string& newFile) {
    // Your implementation goes here
    printf("mvFile\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<distDataHandler> handler(new distDataHandler());
  shared_ptr<TProcessor> processor(new distDataProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

